[package]
name = "try_sin"
version = "0.1.0"
edition = "2021"

[dependencies]
sin = {path = "../sin"}
traits = {path  = "../traits"}
stargate-grpc = {version = "0.4"}
tokio = {version = "1", features = ["full"]}
anyhow = {version =  "*"}

[lints]
workspace = true

